# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animal_store_proto/animal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from animal_store_proto import common_pb2 as animal__store__proto_dot_common__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from validate import validate_pb2 as validate_dot_validate__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animal_store_proto/animal.proto',
  package='animal_store_proto',
  syntax='proto3',
  serialized_pb=_b('\n\x1f\x61nimal_store_proto/animal.proto\x12\x12\x61nimal_store_proto\x1a\x1f\x61nimal_store_proto/common.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\"0\n\tAnimalReq\x12#\n\x08\x61nimalId\x18\x01 \x01(\tB\x07\xfa\x42\x04r\x02\x10\x01R\x08\x61nimalId\"\xad\x01\n\tAnimalRsp\x12\x37\n\x08\x61nimalId\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueR\x08\x61nimalId\x12\x34\n\x06\x61nimal\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValueR\x06\x61nimal\x12\x31\n\x05price\x18\x03 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueR\x05priceB\x16Z\x14./animal_store_protob\x06proto3')
  ,
  dependencies=[animal__store__proto_dot_common__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,validate_dot_validate__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_ANIMALREQ = _descriptor.Descriptor(
  name='AnimalReq',
  full_name='animal_store_proto.AnimalReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='animalId', full_name='animal_store_proto.AnimalReq.animalId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\372B\004r\002\020\001')), json_name='animalId', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=223,
)


_ANIMALRSP = _descriptor.Descriptor(
  name='AnimalRsp',
  full_name='animal_store_proto.AnimalRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='animalId', full_name='animal_store_proto.AnimalRsp.animalId', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='animalId', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='animal', full_name='animal_store_proto.AnimalRsp.animal', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='animal', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='animal_store_proto.AnimalRsp.price', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, json_name='price', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=399,
)

_ANIMALRSP.fields_by_name['animalId'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
_ANIMALRSP.fields_by_name['animal'].message_type = google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE
_ANIMALRSP.fields_by_name['price'].message_type = google_dot_protobuf_dot_wrappers__pb2._INT32VALUE
DESCRIPTOR.message_types_by_name['AnimalReq'] = _ANIMALREQ
DESCRIPTOR.message_types_by_name['AnimalRsp'] = _ANIMALRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnimalReq = _reflection.GeneratedProtocolMessageType('AnimalReq', (_message.Message,), dict(
  DESCRIPTOR = _ANIMALREQ,
  __module__ = 'animal_store_proto.animal_pb2'
  # @@protoc_insertion_point(class_scope:animal_store_proto.AnimalReq)
  ))
_sym_db.RegisterMessage(AnimalReq)

AnimalRsp = _reflection.GeneratedProtocolMessageType('AnimalRsp', (_message.Message,), dict(
  DESCRIPTOR = _ANIMALRSP,
  __module__ = 'animal_store_proto.animal_pb2'
  # @@protoc_insertion_point(class_scope:animal_store_proto.AnimalRsp)
  ))
_sym_db.RegisterMessage(AnimalRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\024./animal_store_proto'))
_ANIMALREQ.fields_by_name['animalId'].has_options = True
_ANIMALREQ.fields_by_name['animalId']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\372B\004r\002\020\001'))
# @@protoc_insertion_point(module_scope)
