// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.5.1
// source: animal_store_proto/animal.proto

package animal_store_proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/golang/protobuf/ptypes/struct"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnimalReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimalId string `protobuf:"bytes,1,opt,name=animalId,proto3" json:"animalId,omitempty"`
}

func (x *AnimalReq) Reset() {
	*x = AnimalReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animal_store_proto_animal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalReq) ProtoMessage() {}

func (x *AnimalReq) ProtoReflect() protoreflect.Message {
	mi := &file_animal_store_proto_animal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalReq.ProtoReflect.Descriptor instead.
func (*AnimalReq) Descriptor() ([]byte, []int) {
	return file_animal_store_proto_animal_proto_rawDescGZIP(), []int{0}
}

func (x *AnimalReq) GetAnimalId() string {
	if x != nil {
		return x.AnimalId
	}
	return ""
}

type AnimalRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimalId *wrappers.Int32Value  `protobuf:"bytes,1,opt,name=animalId,proto3" json:"animalId,omitempty"`
	Animal   *wrappers.StringValue `protobuf:"bytes,2,opt,name=animal,proto3" json:"animal,omitempty"`
	Price    *wrappers.Int32Value  `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *AnimalRsp) Reset() {
	*x = AnimalRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_animal_store_proto_animal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalRsp) ProtoMessage() {}

func (x *AnimalRsp) ProtoReflect() protoreflect.Message {
	mi := &file_animal_store_proto_animal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalRsp.ProtoReflect.Descriptor instead.
func (*AnimalRsp) Descriptor() ([]byte, []int) {
	return file_animal_store_proto_animal_proto_rawDescGZIP(), []int{1}
}

func (x *AnimalRsp) GetAnimalId() *wrappers.Int32Value {
	if x != nil {
		return x.AnimalId
	}
	return nil
}

func (x *AnimalRsp) GetAnimal() *wrappers.StringValue {
	if x != nil {
		return x.Animal
	}
	return nil
}

func (x *AnimalRsp) GetPrice() *wrappers.Int32Value {
	if x != nil {
		return x.Price
	}
	return nil
}

var File_animal_store_proto_animal_proto protoreflect.FileDescriptor

var file_animal_store_proto_animal_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a,
	0x09, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x23, 0x0a, 0x08, 0x61, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x49, 0x64, 0x22,
	0xad, 0x01, 0x0a, 0x09, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x37, 0x0a,
	0x08, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x08, 0x61, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x31, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x42,
	0x16, 0x5a, 0x14, 0x2e, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_animal_store_proto_animal_proto_rawDescOnce sync.Once
	file_animal_store_proto_animal_proto_rawDescData = file_animal_store_proto_animal_proto_rawDesc
)

func file_animal_store_proto_animal_proto_rawDescGZIP() []byte {
	file_animal_store_proto_animal_proto_rawDescOnce.Do(func() {
		file_animal_store_proto_animal_proto_rawDescData = protoimpl.X.CompressGZIP(file_animal_store_proto_animal_proto_rawDescData)
	})
	return file_animal_store_proto_animal_proto_rawDescData
}

var file_animal_store_proto_animal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_animal_store_proto_animal_proto_goTypes = []interface{}{
	(*AnimalReq)(nil),            // 0: animal_store_proto.AnimalReq
	(*AnimalRsp)(nil),            // 1: animal_store_proto.AnimalRsp
	(*wrappers.Int32Value)(nil),  // 2: google.protobuf.Int32Value
	(*wrappers.StringValue)(nil), // 3: google.protobuf.StringValue
}
var file_animal_store_proto_animal_proto_depIdxs = []int32{
	2, // 0: animal_store_proto.AnimalRsp.animalId:type_name -> google.protobuf.Int32Value
	3, // 1: animal_store_proto.AnimalRsp.animal:type_name -> google.protobuf.StringValue
	2, // 2: animal_store_proto.AnimalRsp.price:type_name -> google.protobuf.Int32Value
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_animal_store_proto_animal_proto_init() }
func file_animal_store_proto_animal_proto_init() {
	if File_animal_store_proto_animal_proto != nil {
		return
	}
	file_animal_store_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_animal_store_proto_animal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_animal_store_proto_animal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_animal_store_proto_animal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_animal_store_proto_animal_proto_goTypes,
		DependencyIndexes: file_animal_store_proto_animal_proto_depIdxs,
		MessageInfos:      file_animal_store_proto_animal_proto_msgTypes,
	}.Build()
	File_animal_store_proto_animal_proto = out.File
	file_animal_store_proto_animal_proto_rawDesc = nil
	file_animal_store_proto_animal_proto_goTypes = nil
	file_animal_store_proto_animal_proto_depIdxs = nil
}
